// <auto-generated />
using System;
using BarBotControl.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarBotControl.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231228001707_AddedOptionValue")]
    partial class AddedOptionValue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BarBotControl.Models.ErrorType", b =>
                {
                    b.Property<int>("ErrorTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<bool>("Recoverable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SequenceId")
                        .HasColumnType("int")
                        .HasComment("Recovery Sequence Id");

                    b.HasKey("ErrorTypeId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SequenceId");

                    b.ToTable("ErrorTypes");
                });

            modelBuilder.Entity("BarBotControl.Models.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ModuleId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("BarBotControl.Models.Option", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OptionValue")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("OptionValue")
                        .IsUnique();

                    b.ToTable("Options");
                });

            modelBuilder.Entity("BarBotControl.Models.Sequence", b =>
                {
                    b.Property<int>("SequenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SequenceId");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("BarBotControl.Models.SequenceItem", b =>
                {
                    b.Property<int>("SequenceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceId")
                        .HasColumnType("int");

                    b.HasKey("SequenceItemId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("OptionId");

                    b.HasIndex("SequenceId");

                    b.ToTable("SequenceItem");
                });

            modelBuilder.Entity("BarBotControl.Models.SudoUser", b =>
                {
                    b.Property<int>("SudoUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("SudoUserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("SudoUsers");
                });

            modelBuilder.Entity("BarBotControl.Models.ErrorType", b =>
                {
                    b.HasOne("BarBotControl.Models.Module", "Module")
                        .WithMany("ErrorTypes")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarBotControl.Models.Sequence", "Sequence")
                        .WithMany("ErrorTypes")
                        .HasForeignKey("SequenceId");

                    b.Navigation("Module");

                    b.Navigation("Sequence");
                });

            modelBuilder.Entity("BarBotControl.Models.Option", b =>
                {
                    b.HasOne("BarBotControl.Models.Module", "Module")
                        .WithMany("Options")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BarBotControl.Models.SequenceItem", b =>
                {
                    b.HasOne("BarBotControl.Models.Module", "Module")
                        .WithMany("SequenceItems")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarBotControl.Models.Option", "Option")
                        .WithMany("SequenceItems")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarBotControl.Models.Sequence", "Sequence")
                        .WithMany("SequenceItems")
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Option");

                    b.Navigation("Sequence");
                });

            modelBuilder.Entity("BarBotControl.Models.Module", b =>
                {
                    b.Navigation("ErrorTypes");

                    b.Navigation("Options");

                    b.Navigation("SequenceItems");
                });

            modelBuilder.Entity("BarBotControl.Models.Option", b =>
                {
                    b.Navigation("SequenceItems");
                });

            modelBuilder.Entity("BarBotControl.Models.Sequence", b =>
                {
                    b.Navigation("ErrorTypes");

                    b.Navigation("SequenceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
